TEXT_ALL = "All"

# Path Constants
IMG_PATH = "img\\"
MINER_RES_PATH = IMG_PATH + "miner_res\\"
ICONS_PATH = IMG_PATH + "icons\\"
FARMER_RES_PATH = IMG_PATH + "farmer_res\\"
HERBALIST_RES_PATH = IMG_PATH + "herbalist_res\\"
FISHERMAN_RES_PATH = IMG_PATH + "fisherman_res\\"
LUMBERJACK_RES_PATH = IMG_PATH + "lumberjack_res\\"

# GUI Constants
GUI_FRAME_SELECTJOBANDZONE_TEXT = "< Select profession and Zone >"
GUI_FRAME_SELECTRESOURCE_TEXT = "< Select resource >"
GUI_FRAME_ASSIGNAKEY = "< Assign a key >"

GUI_BUTTON_START_TEXT = "Start"
GUI_BUTTON_STOP_TEXT = "Stop"


# Jobs Constants
JOB_MINER = "Miner"
JOB_LUMBERJACK = "Lumberjack"
JOB_FARMER = "Farmer"
JOB_FISHERMAN = "Fisherman"
JOB_HERBALIST = "Herbalist"
JOB_TRAPPER = "Trapper"

# Zones Constants
ZONE_ASTRUB = "Astrub"
ZONE_AMAKNA = "Amakna"
ZONE_BRAKMAR = "Brakmar"
ZONE_WILD_ESTATE = "Wild Estate"
ZONE_SUFOKIA = "Sufokia"
ZONE_BONTA = "Bonta"

# Statuses Constants
STATUS_WAITING = "Waiting..."
STATUS_ACTIVE = "Active"
STATUS_STOPPED = "Stopped"

# String Key Constants
KEY_STR_F1 = "Key.f1"
KEY_STR_F2 = "Key.f2"
KEY_STR_F3 = "Key.f3"
KEY_STR_F4 = "Key.f4"
KEY_STR_F5 = "Key.f5"
KEY_STR_F6 = "Key.f6"
KEY_STR_F7 = "Key.f7"
KEY_STR_F8 = "Key.f8"
KEY_STR_F9 = "Key.f9"
KEY_STR_F10 = "Key.f10"
KEY_STR_F11 = "Key.f11"
KEY_STR_F12 = "Key.f12"

# Miner Resources

RESOURCE_MINER_IRON = "Iron ore"
RESOURCE_MINER_FINEST_SEA_SALT = "Finest sea salt"
RESOURCE_MINER_CLASSIC_CARBON = "Classic carbon"
RESOURCE_MINER_COPPER = "Copper ore"
RESOURCE_MINER_SHADOWY_COBALT = "Shadowy cobalt"
RESOURCE_MINER_BRONZE_NUGGET = "Bronze nugget ore"

RESOURCE_MINER_RUGGED_QUARTZ = "Rugged quartz"

RESOURCE_MINER_SHARD_OF_FLINT = "Shard of flint"

RESOURCE_MINER_ROYAL_BAUXITE = "Royal bauxite ore"


# Farmer Resources
RESOURCE_FARMER_WHEAT = "Wheat"
RESOURCE_FARMER_ARTICHOKE = "Artichoke"
RESOURCE_FARMER_TUBERBULB = "Tuberbulb"
RESOURCE_FARMER_BARLEY = "Barley"

RESOURCE_FARMER_CAWWOT_PLANT = "Cawwot-plant"
RESOURCE_FARMER_BABBAGE_PLANT = "Babbage-plant"

RESOURCE_FARMER_OATS = "Oats"
RESOURCE_FARMER_MELON = "Melon"

# Herbalist Resources
RESOURCE_HERBALIST_IRISS = "Iriss"
RESOURCE_HERBALIST_CROWNED_THISTLE = "Crowned thistle"
RESOURCE_HERBALIST_PLAIN_FLAX = "Plain flax"
RESOURCE_HERBALIST_WILD_MINT = "Wild mint"

RESOURCE_HERBALIST_SCENTED_CLOVER = "Scented clover"
RESOURCE_HERBALIST_ORCHID_FLOWER = "Orchid flower"

RESOURCE_HERBALIST_FUZZY_FERN = "Fuzzy fern"
RESOURCE_HERBALIST_NOSTRIL_ALGAE = "Nostril algae"

# Lumberjack Resources
RESOURCE_LUMBERJACK_ASH = "Ash"
RESOURCE_LUMBERJACK_HAZEL_TREE = "Hazel tree"
RESOURCE_LUMBERJACK_CHESTNUT_TREE = "Chestnut tree"
RESOURCE_LUMBERJACK_API_TREE = "Api Tree"

RESOURCE_LUMBERJACK_BOABOB = "Boabob"
RESOURCE_LUMBERJACK_BIRCH = "Birch"

RESOURCE_LUMBERJACK_CITRONANA_TREE = "Citronana tree"


# Resources by zone
ZONE_RESOURCES_MINER_ASTRUB = [
    RESOURCE_MINER_IRON,
    RESOURCE_MINER_FINEST_SEA_SALT,
    RESOURCE_MINER_CLASSIC_CARBON,
    RESOURCE_MINER_COPPER,
    RESOURCE_MINER_SHADOWY_COBALT,
]

ZONE_RESOURCES_MINER_WILDESTATE = [
    RESOURCE_MINER_RUGGED_QUARTZ,
]

ZONE_RESOURCES_MINER_BRAKMAR = [
    RESOURCE_MINER_SHARD_OF_FLINT,
]

ZONE_RESOURCES_MINER_BONTA = [
    RESOURCE_MINER_ROYAL_BAUXITE,
]

ZONE_RESOURCES_FARMER_ASTRUB = [
    RESOURCE_FARMER_WHEAT,
    RESOURCE_FARMER_ARTICHOKE,
    RESOURCE_FARMER_TUBERBULB,
    RESOURCE_FARMER_BARLEY,
]

ZONE_RESOURCES_FARMER_AMAKNA = [
    RESOURCE_FARMER_CAWWOT_PLANT,
    RESOURCE_FARMER_BABBAGE_PLANT,
]

ZONE_RESOURCES_FARMER_SUFOKIA = [
    RESOURCE_FARMER_OATS,
    RESOURCE_FARMER_MELON
]


ZONE_RESOURCES_HERBALIST_ASTRUB = [
    RESOURCE_HERBALIST_IRISS,
    RESOURCE_HERBALIST_CROWNED_THISTLE,
    RESOURCE_HERBALIST_PLAIN_FLAX,
    RESOURCE_HERBALIST_WILD_MINT,
]

ZONE_RESOURCES_HERBALIST_AMAKNA = [
    RESOURCE_HERBALIST_SCENTED_CLOVER,
    RESOURCE_HERBALIST_ORCHID_FLOWER,
]

ZONE_RESOURCES_HERBALIST_WILDESTATE = [
    RESOURCE_HERBALIST_FUZZY_FERN,
]

ZONE_RESOURCES_HERBALIST_SUFOKIA = [RESOURCE_HERBALIST_NOSTRIL_ALGAE]

ZONE_RESOURCES_LUMBERJACK_AMAKNA = [
    RESOURCE_LUMBERJACK_BOABOB,
    RESOURCE_LUMBERJACK_BIRCH,
]

ZONE_RESOURCES_LUMBERJACK_ASTRUB = [
    RESOURCE_LUMBERJACK_ASH,
    RESOURCE_LUMBERJACK_HAZEL_TREE,
    RESOURCE_LUMBERJACK_CHESTNUT_TREE,
    RESOURCE_LUMBERJACK_API_TREE,
]

ZONE_RESOURCES_LUMBERJACK_SUFOKIA = [
    RESOURCE_LUMBERJACK_API_TREE,
    RESOURCE_LUMBERJACK_CITRONANA_TREE
]

# Action Icon Names
ICON_ACTION_FARMING_CUT = "cut-icon.png"
ICON_ACTION_FARMING_SEEDS = "harvest-icon.png"
ICON_ACTION_FARMING_REAP = "reap-icon.png"
ICON_ACTION_MINING_HARVEST = "mine-icon.png"
ICON_ACTION_HERBALIST_SEEDS = "harvest-icon.png"
ICON_ACTION_HERBALIST_CUT = "cut-icon.png"
ICON_ACTION_TRAPPER_SEEDS = "trapper-seed-icon.png"
ICON_ACTION_FISHERMAN_FISH = "hook-icon.png"
ICON_ACTION_LUMBERJACK_GET = "get-icon.png"
ICON_ACTION_LUMBERJACK_CUT_TREE = "cut-tree-icon.png"


## Available Actions by resource

ICON_FOR_ACTIONS_FARMER = {
    RESOURCE_FARMER_WHEAT: {
        "harvest": ICON_ACTION_FARMING_REAP,
        "seeds": ICON_ACTION_FARMING_SEEDS,
    },
    RESOURCE_FARMER_ARTICHOKE: {
        "harvest": ICON_ACTION_FARMING_CUT,
        "seeds": ICON_ACTION_FARMING_SEEDS,
    },
    RESOURCE_FARMER_TUBERBULB: {
        "harvest": ICON_ACTION_FARMING_CUT,
        "seeds": ICON_ACTION_FARMING_SEEDS,
    },
    RESOURCE_FARMER_BARLEY: {
        "harvest": ICON_ACTION_FARMING_REAP,
        "seeds": ICON_ACTION_FARMING_SEEDS,
    },
    RESOURCE_FARMER_CAWWOT_PLANT: {
        "harvest": ICON_ACTION_FARMING_CUT,
        "seeds": ICON_ACTION_FARMING_SEEDS,
    },
    RESOURCE_FARMER_BABBAGE_PLANT: {
        "harvest": ICON_ACTION_FARMING_CUT,
        "seeds": ICON_ACTION_FARMING_SEEDS,
    },
    RESOURCE_FARMER_MELON:{
        "harvest": ICON_ACTION_FARMING_CUT,
        "seeds": ICON_ACTION_FARMING_SEEDS
    },
    RESOURCE_FARMER_OATS:{
        "harvest": ICON_ACTION_FARMING_REAP,
        "seeds": ICON_ACTION_FARMING_SEEDS
    }
}
